---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3

env:
  global:
    - CC_TEST_REPORTER_ID=0574ba014fdce356c974c3b8e6e74ea6b07079b9355c35b391b8e17e72aec5c1

apt_packages:
  - bitcoind

before_install:
  - gem install bundler -v 1.16.6
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind -y
  - wget https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-x86_64-linux-gnu.tar.gz
  - tar -xvf litecoin-0.16.3-x86_64-linux-gnu.tar.gz
  - export PATH=./litecoin-0.16.3/bin:$PATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - bitcoind -regtest -daemon
  - litecoind -regtest -daemon
  - sleep 15
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
